rootProject.name = "CopyMangaX"
include(":app")
include(":lib_base")
include(":module_home")
include(":module_main")
include(":module_discover")
include(":module_bookshelf")
include(":module_book")
include(":module_user")
// include(":module_anime")