name: 新功能和建议
description: 提交新功能和改进建议
title: "[Enhancement] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        欢迎提交提交新功能和建议
        > [!IMPORTANT]
        > 请在提交前确保最新版本中无此特性，且无issues重复.
        例如，对于 "漫画下载" 问题，请先搜索关键词，若已有人提出，就去那个议题里点赞即可，无需重复提交。

        > [!IIP]
        > 每个 issue 只提交一个特性
        若有多个特性建议，请分别提交，否则只有第一个建议会被考虑。
        

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请详细描述你想要的功能或改进建议
    validations:
      required: false

- type: input
    id: version
    attributes:
      label: 当前软件版本号
      description: 你正在使用的软件版本号，可在 "设置-关于" 中找到，如 `2.1.1`。
      placeholder: "例如: 2.1.1"
    validations:
      required: true
